libvirt-uri: qemu:///system # how should vagrant connect to libvirt
libvirt-storage-pool: default # which storage pool to use
nodes:
  admin:
  mon1:
  mon2:
  mon3:
  data1:
  data2:
  data3:
  data4:
  data5:
  client1:
  rgw1:
memory:
disks:
  data1:
    hds: 5
    ssds: 1
  data2:
    hds: 5
    ssds: 1
  data3:
    hds: 5
    ssds: 1
  data4:
    hds: 5
    ssds: 1
  data5:
    hds: 5
    ssds: 1
  data6:
    hds: 5
    ssds: 1
packages:
  admin:
    - salt-master
files:
  all: false
  admin: true
commands:
  admin:
  all:
